[build]
  publish = "dist"
  command = "npm run optimize-images && npm run build"

[context.deploy-preview.environment]
  PAGE_TITLE = "[PREVIEW] Travel Log"

# Redirect for incomplete admin urls
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true

# Make react router work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  MAPBOX_TOKEN = "Your Mapbox (mapbox.com) token"
  PAGE_TITLE = "Page Title"
  PAGE_DESCRIPTION = "Page Description"
  GA_TRACKING_ID = "Google Analytics Tracking ID (UA-XXXXXXXX-X)"
