title: This is a sample title
home: >-
  I have been lucky to travel to more than a few places in the world. Lorem
  ipsum




  [](http://localhost:9000/japan)
footer: "**THIS IS NOT A TRAVEL GUIDE.**This is a log of my experiences
  traveling, and so, it shows what I, Naz, experienced and felt in these places.
  You may disagree in many things, and that's ok. You may enjoy similar things
  as me, and then this could help you plan your trip."
